function [Canvas, MainCanvas] = CreateCanvas(x,y)
global CloseReq
global curKey;

        % initWindow - initialize the main window, axes and image objects
        Canvas = figure('Name', ['Pong ' 'V0.1'], ...
            'NumberTitle' ,'off', ...
            'Position', [0,0,x,y], ...
            'Units', 'pixels', ...
            'MenuBar', 'figure', ...
            'Renderer', 'OpenGL',...
            'Color',[0 0 0], ...
            'KeyPressFcn', @stl_KeyPressFcn, ...
            'WindowKeyReleaseFcn', @stl_KeyUp,...
            'CloseRequestFcn', @stl_CloseReqFcn);
        
        
           
        MainCanvas = axes('Parent', Canvas, ...
            'Units', 'pixels',...
            'color', [0 0 0], ...
             'Position', [0,0,x,y], ...
            'XLim', [0 600]-0.5, ...
            'YLim', [0 400]-0.5, ...
            'YDir', 'reverse', ...
            'NextPlot', 'add', ...
            'Visible', 'on', ...
            'XTick',[], ...
            'YTick',[]);
        
    
        
        
    function stl_CloseReqFcn(hObject, eventdata, handles)
        CloseReq = true;
%         delete(Canvas)
%         clear all
%         return
    end

        
        
    function stl_KeyPressFcn(hObject, eventdata, handles)
        
            curKey = get(hObject, 'CurrentKey');
        
    end


    function stl_KeyUp(hObject, eventdata, handles)
        curKey3 = get(hObject, 'CurrentKey');
        if strcmp(curKey3, 'space') ~=1
       curKey = 0;
        end
    end



end